"""empty message

Revision ID: ab4d4473ec13
Revises: e8bc446ca2c1
Create Date: 2018-02-05 13:39:06.329941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4d4473ec13'
down_revision = 'e8bc446ca2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    # ### end Alembic commands ###
